;;; makinda-light-theme.el --- Makinda Light theme  -*- lexical-binding: t; -*-
;;
;; Author: Jackson Makinda
;; URL: https://github.com/makindajack/makinda-themes
;; Generated from source/palette.json. Do not edit by hand.
;;
;;; Commentary:
;;
;; Makinda Light — a premium light theme with warm orange accents.
;;
;;; Code:

(deftheme makinda-light
  "Makinda Light — premium light theme with warm orange accents.")

(custom-theme-set-faces
 'makinda-light
   '(default ((t (:foreground "#27272a" :background "#ffffff"))))
   '(cursor ((t (:background "#e65800"))))
   '(region ((t (:background "#f4f4f5" :extend t))))
   '(highlight ((t (:background "#fafafa"))))
   '(hl-line ((t (:background "#fafafa" :extend t))))
   '(fringe ((t (:background "#ffffff"))))
   '(vertical-border ((t (:foreground "#e4e4e7"))))
   '(window-divider ((t (:foreground "#e4e4e7"))))
   '(window-divider-first-pixel ((t (:foreground "#e4e4e7"))))
   '(window-divider-last-pixel ((t (:foreground "#e4e4e7"))))
   '(minibuffer-prompt ((t (:foreground "#e65800" :weight bold))))
   '(link ((t (:foreground "#0891b2" :underline t))))
   '(link-visited ((t (:foreground "#0891b2" :underline t))))
   '(button ((t (:foreground "#ffffff" :background "#e65800" :weight bold :box (:line-width -1 :color "#e65800")))))
   '(trailing-whitespace ((t (:background "#f4f4f5"))))
   '(show-paren-match ((t (:foreground "#e65800" :weight bold :underline t))))
   '(show-paren-mismatch ((t (:foreground "#ffffff" :background "#f43f5e"))))
   '(isearch ((t (:foreground "#ffffff" :background "#e65800"))))
   '(isearch-fail ((t (:foreground "#ffffff" :background "#f43f5e"))))
   '(lazy-highlight ((t (:background "#f4f4f5"))))
   '(match ((t (:foreground "#e65800" :weight bold))))
   '(mode-line ((t (:foreground "#27272a" :background "#fafafa" :box (:line-width -1 :color "#e4e4e7")))))
   '(mode-line-inactive ((t (:foreground "#52525b" :background "#ffffff" :box (:line-width -1 :color "#e4e4e7")))))
   '(mode-line-emphasis ((t (:foreground "#e65800" :weight bold))))
   '(mode-line-highlight ((t (:foreground "#e65800"))))
   '(header-line ((t (:foreground "#27272a" :background "#fafafa"))))
   '(line-number ((t (:foreground "#a1a1aa" :background "#ffffff"))))
   '(line-number-current-line ((t (:foreground "#e65800" :background "#fafafa" :weight bold))))
   '(line-number-major-tick ((t (:foreground "#52525b"))))
   '(line-number-minor-tick ((t (:foreground "#a1a1aa"))))
   '(font-lock-comment-face ((t (:foreground "#71717a" :slant italic))))
   '(font-lock-comment-delimiter-face ((t (:foreground "#71717a" :slant italic))))
   '(font-lock-doc-face ((t (:foreground "#71717a" :slant italic))))
   '(font-lock-string-face ((t (:foreground "#0d7377"))))
   '(font-lock-keyword-face ((t (:foreground "#b34400"))))
   '(font-lock-builtin-face ((t (:foreground "#853fd9"))))
   '(font-lock-constant-face ((t (:foreground "#853fd9"))))
   '(font-lock-function-name-face ((t (:foreground "#e65800"))))
   '(font-lock-variable-name-face ((t (:foreground "#27272a"))))
   '(font-lock-type-face ((t (:foreground "#6b26c0"))))
   '(font-lock-warning-face ((t (:foreground "#f59e0b" :weight bold))))
   '(font-lock-preprocessor-face ((t (:foreground "#ff9452"))))
   '(font-lock-negation-char-face ((t (:foreground "#b34400"))))
   '(font-lock-regexp-grouping-backslash ((t (:foreground "#0891b2"))))
   '(font-lock-regexp-grouping-construct ((t (:foreground "#0891b2"))))
   '(error ((t (:foreground "#f43f5e" :weight bold))))
   '(warning ((t (:foreground "#f59e0b"))))
   '(success ((t (:foreground "#10b981"))))
   '(font-lock-property-name-face ((t (:foreground "#27272a"))))
   '(font-lock-property-use-face ((t (:foreground "#27272a"))))
   '(font-lock-operator-face ((t (:foreground "#71717a"))))
   '(font-lock-bracket-face ((t (:foreground "#52525b"))))
   '(font-lock-delimiter-face ((t (:foreground "#52525b"))))
   '(font-lock-number-face ((t (:foreground "#ff711a"))))
   '(font-lock-misc-punctuation-face ((t (:foreground "#52525b"))))
   '(font-lock-punctuation-face ((t (:foreground "#52525b"))))
   '(font-lock-escape-face ((t (:foreground "#0891b2"))))
   '(font-lock-function-call-face ((t (:foreground "#e65800"))))
   '(font-lock-function-name-face ((t (:foreground "#e65800"))))
   '(font-lock-variable-use-face ((t (:foreground "#27272a"))))
   '(diff-added ((t (:foreground "#047857" :background "#fafafa" :extend t))))
   '(diff-removed ((t (:foreground "#b34400" :background "#fafafa" :extend t))))
   '(diff-changed ((t (:foreground "#ff9452" :background "#fafafa" :extend t))))
   '(diff-refine-added ((t (:background "#f4f4f5" :foreground "#047857" :weight bold))))
   '(diff-refine-removed ((t (:background "#f4f4f5" :foreground "#b34400" :weight bold))))
   '(diff-refine-changed ((t (:background "#f4f4f5" :foreground "#ff9452" :weight bold))))
   '(diff-header ((t (:foreground "#e65800" :weight bold))))
   '(diff-file-header ((t (:foreground "#e65800" :weight bold))))
   '(ediff-current-diff-A ((t (:background "#fafafa"))))
   '(ediff-current-diff-B ((t (:background "#fafafa"))))
   '(ediff-current-diff-C ((t (:background "#fafafa"))))
   '(ediff-fine-diff-A ((t (:background "#f4f4f5" :weight bold))))
   '(ediff-fine-diff-B ((t (:background "#f4f4f5" :weight bold))))
   '(ediff-fine-diff-C ((t (:background "#f4f4f5" :weight bold))))
   '(magit-section-heading ((t (:foreground "#e65800" :weight bold))))
   '(magit-section-highlight ((t (:background "#fafafa" :extend t))))
   '(magit-diff-added ((t (:foreground "#047857" :background "#fafafa" :extend t))))
   '(magit-diff-added-highlight ((t (:foreground "#047857" :background "#f4f4f5" :extend t))))
   '(magit-diff-removed ((t (:foreground "#b34400" :background "#fafafa" :extend t))))
   '(magit-diff-removed-highlight ((t (:foreground "#b34400" :background "#f4f4f5" :extend t))))
   '(magit-diff-context ((t (:foreground "#52525b" :background "#ffffff" :extend t))))
   '(magit-diff-context-highlight ((t (:foreground "#52525b" :background "#fafafa" :extend t))))
   '(magit-diff-hunk-heading ((t (:foreground "#27272a" :background "#fafafa" :extend t))))
   '(magit-diff-hunk-heading-highlight ((t (:foreground "#27272a" :background "#f4f4f5" :extend t))))
   '(magit-branch-local ((t (:foreground "#e65800"))))
   '(magit-branch-remote ((t (:foreground "#10b981"))))
   '(magit-tag ((t (:foreground "#853fd9"))))
   '(magit-hash ((t (:foreground "#52525b"))))
   '(company-tooltip ((t (:foreground "#27272a" :background "#ffffff"))))
   '(company-tooltip-selection ((t (:foreground "#27272a" :background "#f4f4f5" :weight bold))))
   '(company-tooltip-common ((t (:foreground "#e65800" :weight bold))))
   '(company-tooltip-annotation ((t (:foreground "#52525b"))))
   '(company-scrollbar-bg ((t (:background "#ffffff"))))
   '(company-scrollbar-fg ((t (:background "#d4d4d8"))))
   '(corfu-default ((t (:foreground "#27272a" :background "#ffffff"))))
   '(corfu-current ((t (:foreground "#27272a" :background "#f4f4f5"))))
   '(corfu-bar ((t (:background "#d4d4d8"))))
   '(corfu-border ((t (:background "#e4e4e7"))))
   '(flycheck-error ((t (:underline (:color "#f43f5e" :style wave)))))
   '(flycheck-warning ((t (:underline (:color "#f59e0b" :style wave)))))
   '(flycheck-info ((t (:underline (:color "#3b82f6" :style wave)))))
   '(flymake-error ((t (:underline (:color "#f43f5e" :style wave)))))
   '(flymake-warning ((t (:underline (:color "#f59e0b" :style wave)))))
   '(flymake-note ((t (:underline (:color "#3b82f6" :style wave)))))
   '(org-level-1 ((t (:foreground "#e65800" :weight bold))))
   '(org-level-2 ((t (:foreground "#e65800" :weight bold))))
   '(org-level-3 ((t (:foreground "#e65800" :weight bold))))
   '(org-level-4 ((t (:foreground "#e65800" :weight bold))))
   '(org-level-5 ((t (:foreground "#e65800"))))
   '(org-level-6 ((t (:foreground "#e65800"))))
   '(org-block ((t (:background "#fafafa" :extend t))))
   '(org-code ((t (:foreground "#0d7377"))))
   '(org-verbatim ((t (:foreground "#0d7377"))))
   '(org-quote ((t (:foreground "#71717a" :slant italic))))
   '(org-todo ((t (:foreground "#f59e0b" :weight bold))))
   '(org-done ((t (:foreground "#10b981" :weight bold))))
   '(org-link ((t (:foreground "#0891b2" :underline t))))
   '(org-table ((t (:foreground "#27272a" :background "#fafafa")))))

(custom-theme-set-variables
 'makinda-light
 '(frame-background-mode (quote light)))

;;;###autoload
(when (and (boundp 'custom-theme-load-path) load-file-name)
  (add-to-list 'custom-theme-load-path
               (file-name-as-directory
                (file-name-directory load-file-name))))

(provide-theme 'makinda-light)
;;; makinda-light-theme.el ends here
