;;; makinda-dark-theme.el --- Makinda Dark theme  -*- lexical-binding: t; -*-
;;
;; Author: Jackson Makinda
;; URL: https://github.com/makindajack/makinda-themes
;; Generated from source/palette.json. Do not edit by hand.
;;
;;; Commentary:
;;
;; Makinda Dark — a premium dark theme with warm orange accents.
;;
;;; Code:

(deftheme makinda-dark
  "Makinda Dark — premium dark theme with warm orange accents.")

(custom-theme-set-faces
 'makinda-dark
   '(default ((t (:foreground "#e7e8ea" :background "#0e0e0f"))))
   '(cursor ((t (:background "#ff6b0d"))))
   '(region ((t (:background "#1e2022" :extend t))))
   '(highlight ((t (:background "#161618"))))
   '(hl-line ((t (:background "#161618" :extend t))))
   '(fringe ((t (:background "#0e0e0f"))))
   '(vertical-border ((t (:foreground "#1e2022"))))
   '(window-divider ((t (:foreground "#1e2022"))))
   '(window-divider-first-pixel ((t (:foreground "#1e2022"))))
   '(window-divider-last-pixel ((t (:foreground "#1e2022"))))
   '(minibuffer-prompt ((t (:foreground "#ff6b0d" :weight bold))))
   '(link ((t (:foreground "#22d3ee" :underline t))))
   '(link-visited ((t (:foreground "#22d3ee" :underline t))))
   '(button ((t (:foreground "#ffffff" :background "#ff6b0d" :weight bold :box (:line-width -1 :color "#ff6b0d")))))
   '(trailing-whitespace ((t (:background "#1e2022"))))
   '(show-paren-match ((t (:foreground "#ff6b0d" :weight bold :underline t))))
   '(show-paren-mismatch ((t (:foreground "#ffffff" :background "#ef4444"))))
   '(isearch ((t (:foreground "#ffffff" :background "#ff6b0d"))))
   '(isearch-fail ((t (:foreground "#ffffff" :background "#ef4444"))))
   '(lazy-highlight ((t (:background "#1e2022"))))
   '(match ((t (:foreground "#ff6b0d" :weight bold))))
   '(mode-line ((t (:foreground "#e7e8ea" :background "#161618" :box (:line-width -1 :color "#1e2022")))))
   '(mode-line-inactive ((t (:foreground "#969ba6" :background "#0e0e0f" :box (:line-width -1 :color "#1e2022")))))
   '(mode-line-emphasis ((t (:foreground "#ff6b0d" :weight bold))))
   '(mode-line-highlight ((t (:foreground "#ff6b0d"))))
   '(header-line ((t (:foreground "#e7e8ea" :background "#161618"))))
   '(line-number ((t (:foreground "#474b54" :background "#0e0e0f"))))
   '(line-number-current-line ((t (:foreground "#ff6b0d" :background "#161618" :weight bold))))
   '(line-number-major-tick ((t (:foreground "#969ba6"))))
   '(line-number-minor-tick ((t (:foreground "#474b54"))))
   '(font-lock-comment-face ((t (:foreground "#7d8593" :slant italic))))
   '(font-lock-comment-delimiter-face ((t (:foreground "#7d8593" :slant italic))))
   '(font-lock-doc-face ((t (:foreground "#7d8593" :slant italic))))
   '(font-lock-string-face ((t (:foreground "#2dd4bf"))))
   '(font-lock-keyword-face ((t (:foreground "#ff6b0d"))))
   '(font-lock-builtin-face ((t (:foreground "#b88ef2"))))
   '(font-lock-constant-face ((t (:foreground "#b88ef2"))))
   '(font-lock-function-name-face ((t (:foreground "#ff8d37"))))
   '(font-lock-variable-name-face ((t (:foreground "#e7e8ea"))))
   '(font-lock-type-face ((t (:foreground "#a78bfa"))))
   '(font-lock-warning-face ((t (:foreground "#f59e0b" :weight bold))))
   '(font-lock-preprocessor-face ((t (:foreground "#ffb770"))))
   '(font-lock-negation-char-face ((t (:foreground "#ff6b0d"))))
   '(font-lock-regexp-grouping-backslash ((t (:foreground "#22d3ee"))))
   '(font-lock-regexp-grouping-construct ((t (:foreground "#22d3ee"))))
   '(error ((t (:foreground "#ef4444" :weight bold))))
   '(warning ((t (:foreground "#f59e0b"))))
   '(success ((t (:foreground "#22c55e"))))
   '(font-lock-property-name-face ((t (:foreground "#e7e8ea"))))
   '(font-lock-property-use-face ((t (:foreground "#e7e8ea"))))
   '(font-lock-operator-face ((t (:foreground "#969ba6"))))
   '(font-lock-bracket-face ((t (:foreground "#969ba6"))))
   '(font-lock-delimiter-face ((t (:foreground "#969ba6"))))
   '(font-lock-number-face ((t (:foreground "#ff6b0d"))))
   '(font-lock-misc-punctuation-face ((t (:foreground "#969ba6"))))
   '(font-lock-punctuation-face ((t (:foreground "#969ba6"))))
   '(font-lock-escape-face ((t (:foreground "#22d3ee"))))
   '(font-lock-function-call-face ((t (:foreground "#ff8d37"))))
   '(font-lock-function-name-face ((t (:foreground "#ff8d37"))))
   '(font-lock-variable-use-face ((t (:foreground "#e7e8ea"))))
   '(diff-added ((t (:foreground "#4ade80" :background "#161618" :extend t))))
   '(diff-removed ((t (:foreground "#ff6b0d" :background "#161618" :extend t))))
   '(diff-changed ((t (:foreground "#ffb770" :background "#161618" :extend t))))
   '(diff-refine-added ((t (:background "#1e2022" :foreground "#4ade80" :weight bold))))
   '(diff-refine-removed ((t (:background "#1e2022" :foreground "#ff6b0d" :weight bold))))
   '(diff-refine-changed ((t (:background "#1e2022" :foreground "#ffb770" :weight bold))))
   '(diff-header ((t (:foreground "#ff8d37" :weight bold))))
   '(diff-file-header ((t (:foreground "#ff8d37" :weight bold))))
   '(ediff-current-diff-A ((t (:background "#161618"))))
   '(ediff-current-diff-B ((t (:background "#161618"))))
   '(ediff-current-diff-C ((t (:background "#161618"))))
   '(ediff-fine-diff-A ((t (:background "#1e2022" :weight bold))))
   '(ediff-fine-diff-B ((t (:background "#1e2022" :weight bold))))
   '(ediff-fine-diff-C ((t (:background "#1e2022" :weight bold))))
   '(magit-section-heading ((t (:foreground "#ff8d37" :weight bold))))
   '(magit-section-highlight ((t (:background "#161618" :extend t))))
   '(magit-diff-added ((t (:foreground "#4ade80" :background "#161618" :extend t))))
   '(magit-diff-added-highlight ((t (:foreground "#4ade80" :background "#1e2022" :extend t))))
   '(magit-diff-removed ((t (:foreground "#ff6b0d" :background "#161618" :extend t))))
   '(magit-diff-removed-highlight ((t (:foreground "#ff6b0d" :background "#1e2022" :extend t))))
   '(magit-diff-context ((t (:foreground "#969ba6" :background "#0e0e0f" :extend t))))
   '(magit-diff-context-highlight ((t (:foreground "#969ba6" :background "#161618" :extend t))))
   '(magit-diff-hunk-heading ((t (:foreground "#e7e8ea" :background "#161618" :extend t))))
   '(magit-diff-hunk-heading-highlight ((t (:foreground "#e7e8ea" :background "#1e2022" :extend t))))
   '(magit-branch-local ((t (:foreground "#ff6b0d"))))
   '(magit-branch-remote ((t (:foreground "#22c55e"))))
   '(magit-tag ((t (:foreground "#b88ef2"))))
   '(magit-hash ((t (:foreground "#969ba6"))))
   '(company-tooltip ((t (:foreground "#e7e8ea" :background "#1e2022"))))
   '(company-tooltip-selection ((t (:foreground "#e7e8ea" :background "#1e2022" :weight bold))))
   '(company-tooltip-common ((t (:foreground "#ff6b0d" :weight bold))))
   '(company-tooltip-annotation ((t (:foreground "#969ba6"))))
   '(company-scrollbar-bg ((t (:background "#1e2022"))))
   '(company-scrollbar-fg ((t (:background "#36393f"))))
   '(corfu-default ((t (:foreground "#e7e8ea" :background "#1e2022"))))
   '(corfu-current ((t (:foreground "#e7e8ea" :background "#1e2022"))))
   '(corfu-bar ((t (:background "#36393f"))))
   '(corfu-border ((t (:background "#1e2022"))))
   '(flycheck-error ((t (:underline (:color "#ef4444" :style wave)))))
   '(flycheck-warning ((t (:underline (:color "#f59e0b" :style wave)))))
   '(flycheck-info ((t (:underline (:color "#3b82f6" :style wave)))))
   '(flymake-error ((t (:underline (:color "#ef4444" :style wave)))))
   '(flymake-warning ((t (:underline (:color "#f59e0b" :style wave)))))
   '(flymake-note ((t (:underline (:color "#3b82f6" :style wave)))))
   '(org-level-1 ((t (:foreground "#ff8d37" :weight bold))))
   '(org-level-2 ((t (:foreground "#ff8d37" :weight bold))))
   '(org-level-3 ((t (:foreground "#ff8d37" :weight bold))))
   '(org-level-4 ((t (:foreground "#ff8d37" :weight bold))))
   '(org-level-5 ((t (:foreground "#ff8d37"))))
   '(org-level-6 ((t (:foreground "#ff8d37"))))
   '(org-block ((t (:background "#161618" :extend t))))
   '(org-code ((t (:foreground "#2dd4bf"))))
   '(org-verbatim ((t (:foreground "#2dd4bf"))))
   '(org-quote ((t (:foreground "#7d8593" :slant italic))))
   '(org-todo ((t (:foreground "#f59e0b" :weight bold))))
   '(org-done ((t (:foreground "#22c55e" :weight bold))))
   '(org-link ((t (:foreground "#22d3ee" :underline t))))
   '(org-table ((t (:foreground "#e7e8ea" :background "#161618")))))

(custom-theme-set-variables
 'makinda-dark
 '(frame-background-mode (quote dark)))

;;;###autoload
(when (and (boundp 'custom-theme-load-path) load-file-name)
  (add-to-list 'custom-theme-load-path
               (file-name-as-directory
                (file-name-directory load-file-name))))

(provide-theme 'makinda-dark)
;;; makinda-dark-theme.el ends here
