;;; makinda-light-theme.el --- Makinda Light theme  -*- lexical-binding: t; -*-
;;
;; Author: Jackson Makinda
;; URL: https://github.com/makindajack/makinda-themes
;; Generated from source/palette.json. Do not edit by hand.
;;
;;; Commentary:
;;
;; Makinda Light — a premium light theme with warm orange accents.
;;
;;; Code:

(deftheme makinda-light
  "Makinda Light — premium light theme with warm orange accents.")

(custom-theme-set-faces
 'makinda-light
   '(default ((t (:foreground "#1e2022" :background "#ffffff"))))
   '(cursor ((t (:background "#f05106"))))
   '(region ((t (:background "#f3f3f5" :extend t))))
   '(highlight ((t (:background "#f9f9fa"))))
   '(hl-line ((t (:background "#f9f9fa" :extend t))))
   '(fringe ((t (:background "#ffffff"))))
   '(vertical-border ((t (:foreground "#e7e8ea"))))
   '(window-divider ((t (:foreground "#e7e8ea"))))
   '(window-divider-first-pixel ((t (:foreground "#e7e8ea"))))
   '(window-divider-last-pixel ((t (:foreground "#e7e8ea"))))
   '(minibuffer-prompt ((t (:foreground "#f05106" :weight bold))))
   '(link ((t (:foreground "#0891b2" :underline t))))
   '(link-visited ((t (:foreground "#0891b2" :underline t))))
   '(button ((t (:foreground "#ffffff" :background "#f05106" :weight bold :box (:line-width -1 :color "#f05106")))))
   '(trailing-whitespace ((t (:background "#f3f3f5"))))
   '(show-paren-match ((t (:foreground "#f05106" :weight bold :underline t))))
   '(show-paren-mismatch ((t (:foreground "#ffffff" :background "#ef4444"))))
   '(isearch ((t (:foreground "#ffffff" :background "#f05106"))))
   '(isearch-fail ((t (:foreground "#ffffff" :background "#ef4444"))))
   '(lazy-highlight ((t (:background "#f3f3f5"))))
   '(match ((t (:foreground "#f05106" :weight bold))))
   '(mode-line ((t (:foreground "#1e2022" :background "#f9f9fa" :box (:line-width -1 :color "#e7e8ea")))))
   '(mode-line-inactive ((t (:foreground "#474b54" :background "#ffffff" :box (:line-width -1 :color "#e7e8ea")))))
   '(mode-line-emphasis ((t (:foreground "#f05106" :weight bold))))
   '(mode-line-highlight ((t (:foreground "#f05106"))))
   '(header-line ((t (:foreground "#1e2022" :background "#f9f9fa"))))
   '(line-number ((t (:foreground "#969ba6" :background "#ffffff"))))
   '(line-number-current-line ((t (:foreground "#f05106" :background "#f9f9fa" :weight bold))))
   '(line-number-major-tick ((t (:foreground "#474b54"))))
   '(line-number-minor-tick ((t (:foreground "#969ba6"))))
   '(font-lock-comment-face ((t (:foreground "#6b7280" :slant italic))))
   '(font-lock-comment-delimiter-face ((t (:foreground "#6b7280" :slant italic))))
   '(font-lock-doc-face ((t (:foreground "#6b7280" :slant italic))))
   '(font-lock-string-face ((t (:foreground "#0d7377"))))
   '(font-lock-keyword-face ((t (:foreground "#c73b07"))))
   '(font-lock-builtin-face ((t (:foreground "#8947db"))))
   '(font-lock-constant-face ((t (:foreground "#8947db"))))
   '(font-lock-function-name-face ((t (:foreground "#f05106"))))
   '(font-lock-variable-name-face ((t (:foreground "#1e2022"))))
   '(font-lock-type-face ((t (:foreground "#7c3aed"))))
   '(font-lock-warning-face ((t (:foreground "#f59e0b" :weight bold))))
   '(font-lock-preprocessor-face ((t (:foreground "#ff8d37"))))
   '(font-lock-negation-char-face ((t (:foreground "#c73b07"))))
   '(font-lock-regexp-grouping-backslash ((t (:foreground "#0891b2"))))
   '(font-lock-regexp-grouping-construct ((t (:foreground "#0891b2"))))
   '(error ((t (:foreground "#ef4444" :weight bold))))
   '(warning ((t (:foreground "#f59e0b"))))
   '(success ((t (:foreground "#22c55e"))))
   '(font-lock-property-name-face ((t (:foreground "#1e2022"))))
   '(font-lock-property-use-face ((t (:foreground "#1e2022"))))
   '(font-lock-operator-face ((t (:foreground "#6b7280"))))
   '(font-lock-bracket-face ((t (:foreground "#474b54"))))
   '(font-lock-delimiter-face ((t (:foreground "#474b54"))))
   '(font-lock-number-face ((t (:foreground "#ff6b0d"))))
   '(font-lock-misc-punctuation-face ((t (:foreground "#474b54"))))
   '(font-lock-punctuation-face ((t (:foreground "#474b54"))))
   '(font-lock-escape-face ((t (:foreground "#0891b2"))))
   '(font-lock-function-call-face ((t (:foreground "#f05106"))))
   '(font-lock-function-name-face ((t (:foreground "#f05106"))))
   '(font-lock-variable-use-face ((t (:foreground "#1e2022"))))
   '(diff-added ((t (:foreground "#587c0c" :background "#f9f9fa" :extend t))))
   '(diff-removed ((t (:foreground "#c73b07" :background "#f9f9fa" :extend t))))
   '(diff-changed ((t (:foreground "#ff8d37" :background "#f9f9fa" :extend t))))
   '(diff-refine-added ((t (:background "#f3f3f5" :foreground "#587c0c" :weight bold))))
   '(diff-refine-removed ((t (:background "#f3f3f5" :foreground "#c73b07" :weight bold))))
   '(diff-refine-changed ((t (:background "#f3f3f5" :foreground "#ff8d37" :weight bold))))
   '(diff-header ((t (:foreground "#f05106" :weight bold))))
   '(diff-file-header ((t (:foreground "#f05106" :weight bold))))
   '(ediff-current-diff-A ((t (:background "#f9f9fa"))))
   '(ediff-current-diff-B ((t (:background "#f9f9fa"))))
   '(ediff-current-diff-C ((t (:background "#f9f9fa"))))
   '(ediff-fine-diff-A ((t (:background "#f3f3f5" :weight bold))))
   '(ediff-fine-diff-B ((t (:background "#f3f3f5" :weight bold))))
   '(ediff-fine-diff-C ((t (:background "#f3f3f5" :weight bold))))
   '(magit-section-heading ((t (:foreground "#f05106" :weight bold))))
   '(magit-section-highlight ((t (:background "#f9f9fa" :extend t))))
   '(magit-diff-added ((t (:foreground "#587c0c" :background "#f9f9fa" :extend t))))
   '(magit-diff-added-highlight ((t (:foreground "#587c0c" :background "#f3f3f5" :extend t))))
   '(magit-diff-removed ((t (:foreground "#c73b07" :background "#f9f9fa" :extend t))))
   '(magit-diff-removed-highlight ((t (:foreground "#c73b07" :background "#f3f3f5" :extend t))))
   '(magit-diff-context ((t (:foreground "#474b54" :background "#ffffff" :extend t))))
   '(magit-diff-context-highlight ((t (:foreground "#474b54" :background "#f9f9fa" :extend t))))
   '(magit-diff-hunk-heading ((t (:foreground "#1e2022" :background "#f9f9fa" :extend t))))
   '(magit-diff-hunk-heading-highlight ((t (:foreground "#1e2022" :background "#f3f3f5" :extend t))))
   '(magit-branch-local ((t (:foreground "#f05106"))))
   '(magit-branch-remote ((t (:foreground "#22c55e"))))
   '(magit-tag ((t (:foreground "#8947db"))))
   '(magit-hash ((t (:foreground "#474b54"))))
   '(company-tooltip ((t (:foreground "#1e2022" :background "#ffffff"))))
   '(company-tooltip-selection ((t (:foreground "#1e2022" :background "#f3f3f5" :weight bold))))
   '(company-tooltip-common ((t (:foreground "#f05106" :weight bold))))
   '(company-tooltip-annotation ((t (:foreground "#474b54"))))
   '(company-scrollbar-bg ((t (:background "#ffffff"))))
   '(company-scrollbar-fg ((t (:background "#d1d5db"))))
   '(corfu-default ((t (:foreground "#1e2022" :background "#ffffff"))))
   '(corfu-current ((t (:foreground "#1e2022" :background "#f3f3f5"))))
   '(corfu-bar ((t (:background "#d1d5db"))))
   '(corfu-border ((t (:background "#e7e8ea"))))
   '(flycheck-error ((t (:underline (:color "#ef4444" :style wave)))))
   '(flycheck-warning ((t (:underline (:color "#f59e0b" :style wave)))))
   '(flycheck-info ((t (:underline (:color "#3b82f6" :style wave)))))
   '(flymake-error ((t (:underline (:color "#ef4444" :style wave)))))
   '(flymake-warning ((t (:underline (:color "#f59e0b" :style wave)))))
   '(flymake-note ((t (:underline (:color "#3b82f6" :style wave)))))
   '(org-level-1 ((t (:foreground "#f05106" :weight bold))))
   '(org-level-2 ((t (:foreground "#f05106" :weight bold))))
   '(org-level-3 ((t (:foreground "#f05106" :weight bold))))
   '(org-level-4 ((t (:foreground "#f05106" :weight bold))))
   '(org-level-5 ((t (:foreground "#f05106"))))
   '(org-level-6 ((t (:foreground "#f05106"))))
   '(org-block ((t (:background "#f9f9fa" :extend t))))
   '(org-code ((t (:foreground "#0d7377"))))
   '(org-verbatim ((t (:foreground "#0d7377"))))
   '(org-quote ((t (:foreground "#6b7280" :slant italic))))
   '(org-todo ((t (:foreground "#f59e0b" :weight bold))))
   '(org-done ((t (:foreground "#22c55e" :weight bold))))
   '(org-link ((t (:foreground "#0891b2" :underline t))))
   '(org-table ((t (:foreground "#1e2022" :background "#f9f9fa")))))

(custom-theme-set-variables
 'makinda-light
 '(frame-background-mode (quote light)))

;;;###autoload
(when (and (boundp 'custom-theme-load-path) load-file-name)
  (add-to-list 'custom-theme-load-path
               (file-name-as-directory
                (file-name-directory load-file-name))))

(provide-theme 'makinda-light)
;;; makinda-light-theme.el ends here
