-- Generated from source/palette.json. Do not edit by hand.
local M = {}

function M.get(p)
    local hi = {}
    local function set(name, opts) hi[name] = opts end

    -- ---------- Editor surface ----------
    set("Normal",            { fg = p.fg, bg = p.bg })
    set("NormalNC",          { fg = p.fg, bg = p.bg })
    set("NormalFloat",       { fg = p.fg, bg = p.bg_menu })
    set("FloatBorder",       { fg = p.border_strong, bg = p.bg_menu })
    set("FloatTitle",        { fg = p.primary, bg = p.bg_menu, bold = true })
    set("Cursor",            { fg = p.bg, bg = p.primary })
    set("CursorLine",        { bg = p.bg_elev1 })
    set("CursorColumn",      { bg = p.bg_elev1 })
    set("CursorLineNr",      { fg = p.primary, bold = true })
    set("LineNr",            { fg = p.fg_disabled })
    set("LineNrAbove",       { fg = p.fg_disabled })
    set("LineNrBelow",       { fg = p.fg_disabled })
    set("SignColumn",        { bg = p.bg })
    set("FoldColumn",        { fg = p.fg_disabled, bg = p.bg })
    set("Folded",            { fg = p.fg_muted, bg = p.bg_elev1 })
    set("ColorColumn",       { bg = p.bg_elev1 })
    set("Visual",            { bg = p.bg_elev2 })
    set("VisualNOS",         { bg = p.bg_elev2 })
    set("MatchParen",        { fg = p.primary, bold = true, underline = true })
    set("Conceal",           { fg = p.fg_muted })
    set("NonText",           { fg = p.fg_disabled })
    set("Whitespace",        { fg = p.fg_disabled })
    set("SpecialKey",        { fg = p.fg_disabled })
    set("EndOfBuffer",       { fg = p.bg })

    -- ---------- Search / IncSearch ----------
    set("Search",            { fg = p.fg, bg = p.selection })
    set("IncSearch",         { fg = p.fg_inverse, bg = p.primary })
    set("CurSearch",         { fg = p.fg_inverse, bg = p.primary })
    set("Substitute",        { fg = p.fg_inverse, bg = p.primary_hover })

    -- ---------- Statusline / Tabline / Winbar ----------
    set("StatusLine",        { fg = p.fg, bg = p.bg })
    set("StatusLineNC",      { fg = p.fg_muted, bg = p.bg })
    set("TabLine",           { fg = p.fg_muted, bg = p.bg_elev1 })
    set("TabLineFill",       { bg = p.bg })
    set("TabLineSel",        { fg = p.fg, bg = p.bg, bold = true })
    set("WinBar",            { fg = p.fg, bg = p.bg })
    set("WinBarNC",          { fg = p.fg_muted, bg = p.bg })
    set("WinSeparator",      { fg = p.border })
    set("VertSplit",         { fg = p.border })

    -- ---------- Popup / Pmenu ----------
    set("Pmenu",             { fg = p.fg, bg = p.bg_menu })
    set("PmenuSel",          { fg = p.fg, bg = p.bg_elev2, bold = true })
    set("PmenuSbar",         { bg = p.bg_elev1 })
    set("PmenuThumb",        { bg = p.border_strong })
    set("PmenuKind",         { fg = p.primary, bg = p.bg_menu })
    set("PmenuKindSel",      { fg = p.primary, bg = p.bg_elev2, bold = true })
    set("PmenuExtra",        { fg = p.fg_muted, bg = p.bg_menu })
    set("PmenuExtraSel",     { fg = p.fg_muted, bg = p.bg_elev2 })
    set("WildMenu",          { fg = p.fg, bg = p.bg_elev2 })

    -- ---------- Messages ----------
    set("ErrorMsg",          { fg = p.error })
    set("WarningMsg",        { fg = p.warning })
    set("MoreMsg",           { fg = p.success })
    set("ModeMsg",           { fg = p.fg, bold = true })
    set("MsgArea",           { fg = p.fg, bg = p.bg })
    set("MsgSeparator",      { fg = p.border, bg = p.bg })
    set("Question",          { fg = p.info })
    set("Title",             { fg = p.markup_heading, bold = true })
    set("Directory",         { fg = p.primary })

    -- ---------- Spell ----------
    set("SpellBad",          { sp = p.error,   undercurl = true })
    set("SpellCap",          { sp = p.warning, undercurl = true })
    set("SpellRare",         { sp = p.info,    undercurl = true })
    set("SpellLocal",        { sp = p.info,    undercurl = true })

    -- ---------- Diff ----------
    set("DiffAdd",           { fg = p.diff_added,   bg = p.bg_elev1 })
    set("DiffChange",        { fg = p.diff_changed, bg = p.bg_elev1 })
    set("DiffDelete",        { fg = p.diff_removed, bg = p.bg_elev1 })
    set("DiffText",          { fg = p.diff_changed, bg = p.bg_elev2, bold = true })

    -- ---------- Syntax (legacy, fallback when Treesitter is off) ----------
    set("Comment",           { fg = p.comment, italic = true })
    set("Constant",          { fg = p.constant })
    set("String",            { fg = p.string })
    set("Character",         { fg = p.string })
    set("Number",            { fg = p.number })
    set("Boolean",           { fg = p.constant })
    set("Float",             { fg = p.number })
    set("Identifier",        { fg = p.variable })
    set("Function",          { fg = p.fn })
    set("Statement",         { fg = p.kw })
    set("Conditional",       { fg = p.kw })
    set("Repeat",            { fg = p.kw })
    set("Label",             { fg = p.kw })
    set("Operator",          { fg = p.operator })
    set("Keyword",           { fg = p.kw })
    set("Exception",         { fg = p.kw })
    set("PreProc",           { fg = p.decorator })
    set("Include",           { fg = p.kw })
    set("Define",            { fg = p.kw })
    set("Macro",             { fg = p.decorator })
    set("PreCondit",         { fg = p.kw })
    set("Type",              { fg = p.type })
    set("StorageClass",      { fg = p.kw })
    set("Structure",         { fg = p.type })
    set("Typedef",           { fg = p.type })
    set("Special",           { fg = p.string_escape })
    set("SpecialChar",       { fg = p.string_escape })
    set("SpecialComment",    { fg = p.comment, italic = true })
    set("Tag",               { fg = p.tag })
    set("Delimiter",         { fg = p.punctuation })
    set("Debug",             { fg = p.warning })
    set("Underlined",        { fg = p.markup_link, underline = true })
    set("Error",             { fg = p.error })
    set("Todo",              { fg = p.bg, bg = p.warning, bold = true })

    -- ---------- Treesitter (modern @groups) ----------
    set("@variable",                 { fg = p.variable })
    set("@variable.builtin",         { fg = p.language_variable, italic = true })
    set("@variable.parameter",       { fg = p.parameter, italic = true })
    set("@variable.member",          { fg = p.variable })
    set("@constant",                 { fg = p.constant })
    set("@constant.builtin",         { fg = p.constant })
    set("@constant.macro",           { fg = p.decorator })
    set("@module",                   { fg = p.namespace })
    set("@module.builtin",           { fg = p.namespace })
    set("@label",                    { fg = p.kw })
    set("@string",                   { fg = p.string })
    set("@string.documentation",     { fg = p.comment, italic = true })
    set("@string.regexp",            { fg = p.regex })
    set("@string.escape",            { fg = p.string_escape })
    set("@string.special",           { fg = p.string_escape })
    set("@string.special.url",       { fg = p.markup_link, underline = true })
    set("@character",                { fg = p.string })
    set("@character.special",        { fg = p.string_escape })
    set("@boolean",                  { fg = p.constant })
    set("@number",                   { fg = p.number })
    set("@number.float",             { fg = p.number })
    set("@type",                     { fg = p.type })
    set("@type.builtin",             { fg = p.type })
    set("@type.definition",          { fg = p.type })
    set("@attribute",                { fg = p.decorator })
    set("@attribute.builtin",        { fg = p.decorator })
    set("@property",                 { fg = p.variable })
    set("@function",                 { fg = p.fn })
    set("@function.builtin",         { fg = p.fn })
    set("@function.call",            { fg = p.fn })
    set("@function.macro",           { fg = p.decorator })
    set("@function.method",          { fg = p.fn })
    set("@function.method.call",     { fg = p.fn })
    set("@constructor",              { fg = p.type })
    set("@operator",                 { fg = p.operator })
    set("@keyword",                  { fg = p.kw })
    set("@keyword.coroutine",        { fg = p.kw })
    set("@keyword.function",         { fg = p.kw })
    set("@keyword.operator",         { fg = p.operator })
    set("@keyword.import",           { fg = p.kw })
    set("@keyword.type",             { fg = p.kw })
    set("@keyword.modifier",         { fg = p.kw })
    set("@keyword.repeat",           { fg = p.kw })
    set("@keyword.return",           { fg = p.kw })
    set("@keyword.debug",            { fg = p.warning })
    set("@keyword.exception",        { fg = p.kw })
    set("@keyword.conditional",      { fg = p.kw })
    set("@keyword.directive",        { fg = p.decorator })
    set("@keyword.directive.define", { fg = p.kw })
    set("@punctuation.delimiter",    { fg = p.punctuation })
    set("@punctuation.bracket",      { fg = p.punctuation })
    set("@punctuation.special",      { fg = p.kw })
    set("@comment",                  { fg = p.comment, italic = true })
    set("@comment.documentation",    { fg = p.comment, italic = true })
    set("@comment.error",            { fg = p.error, bold = true })
    set("@comment.warning",          { fg = p.warning, bold = true })
    set("@comment.todo",             { fg = p.warning, bold = true })
    set("@comment.note",             { fg = p.info, bold = true })
    set("@markup.strong",            { fg = p.markup_heading, bold = true })
    set("@markup.italic",            { fg = p.kw, italic = true })
    set("@markup.strikethrough",     { strikethrough = true })
    set("@markup.underline",         { underline = true })
    set("@markup.heading",           { fg = p.markup_heading, bold = true })
    set("@markup.heading.1",         { fg = p.markup_heading, bold = true })
    set("@markup.heading.2",         { fg = p.markup_heading, bold = true })
    set("@markup.heading.3",         { fg = p.markup_heading, bold = true })
    set("@markup.heading.4",         { fg = p.markup_heading, bold = true })
    set("@markup.heading.5",         { fg = p.markup_heading, bold = true })
    set("@markup.heading.6",         { fg = p.markup_heading, bold = true })
    set("@markup.quote",             { fg = p.markup_quote, italic = true })
    set("@markup.math",              { fg = p.constant })
    set("@markup.environment",       { fg = p.kw })
    set("@markup.link",              { fg = p.markup_link })
    set("@markup.link.label",        { fg = p.markup_link })
    set("@markup.link.url",          { fg = p.markup_link, underline = true })
    set("@markup.raw",               { fg = p.markup_code })
    set("@markup.raw.block",         { fg = p.markup_code })
    set("@markup.list",              { fg = p.markup_heading })
    set("@markup.list.checked",      { fg = p.success })
    set("@markup.list.unchecked",    { fg = p.fg_muted })
    set("@diff.plus",                { fg = p.diff_added })
    set("@diff.minus",               { fg = p.diff_removed })
    set("@diff.delta",               { fg = p.diff_changed })
    set("@tag",                      { fg = p.tag })
    set("@tag.builtin",              { fg = p.tag })
    set("@tag.attribute",            { fg = p.attribute })
    set("@tag.delimiter",            { fg = p.punctuation })

    -- ---------- LSP semantic tokens ----------
    set("@lsp.type.namespace",      { link = "@module" })
    set("@lsp.type.type",           { link = "@type" })
    set("@lsp.type.class",          { link = "@type" })
    set("@lsp.type.enum",           { link = "@type" })
    set("@lsp.type.interface",      { link = "@type" })
    set("@lsp.type.struct",         { link = "@type" })
    set("@lsp.type.parameter",      { link = "@variable.parameter" })
    set("@lsp.type.variable",       { link = "@variable" })
    set("@lsp.type.property",       { link = "@property" })
    set("@lsp.type.enumMember",     { link = "@constant" })
    set("@lsp.type.event",          { link = "@type" })
    set("@lsp.type.function",       { link = "@function" })
    set("@lsp.type.method",         { link = "@function.method" })
    set("@lsp.type.macro",          { link = "@function.macro" })
    set("@lsp.type.decorator",      { link = "@attribute" })
    set("@lsp.type.keyword",        { link = "@keyword" })
    set("@lsp.type.modifier",       { link = "@keyword.modifier" })
    set("@lsp.type.comment",        { link = "@comment" })
    set("@lsp.type.string",         { link = "@string" })
    set("@lsp.type.number",         { link = "@number" })
    set("@lsp.type.regexp",         { link = "@string.regexp" })
    set("@lsp.type.operator",       { link = "@operator" })
    set("@lsp.typemod.variable.readonly",      { fg = p.fn })
    set("@lsp.typemod.variable.defaultLibrary",{ fg = p.language_variable, italic = true })
    set("@lsp.typemod.function.defaultLibrary",{ link = "@function.builtin" })
    set("@lsp.typemod.method.defaultLibrary",  { link = "@function.builtin" })

    -- ---------- Diagnostics ----------
    set("DiagnosticError",         { fg = p.error })
    set("DiagnosticWarn",          { fg = p.warning })
    set("DiagnosticInfo",          { fg = p.info })
    set("DiagnosticHint",          { fg = p.fg_muted })
    set("DiagnosticOk",            { fg = p.success })
    set("DiagnosticUnnecessary",   { fg = p.fg_disabled })
    set("DiagnosticDeprecated",    { fg = p.fg_disabled, strikethrough = true })
    set("DiagnosticUnderlineError",{ sp = p.error,   undercurl = true })
    set("DiagnosticUnderlineWarn", { sp = p.warning, undercurl = true })
    set("DiagnosticUnderlineInfo", { sp = p.info,    undercurl = true })
    set("DiagnosticUnderlineHint", { sp = p.fg_muted,undercurl = true })
    set("DiagnosticVirtualTextError", { fg = p.error,   bg = p.bg })
    set("DiagnosticVirtualTextWarn",  { fg = p.warning, bg = p.bg })
    set("DiagnosticVirtualTextInfo",  { fg = p.info,    bg = p.bg })
    set("DiagnosticVirtualTextHint",  { fg = p.fg_muted,bg = p.bg })
    set("DiagnosticSignError",     { fg = p.error })
    set("DiagnosticSignWarn",      { fg = p.warning })
    set("DiagnosticSignInfo",      { fg = p.info })
    set("DiagnosticSignHint",      { fg = p.fg_muted })

    -- ---------- LSP misc ----------
    set("LspReferenceText",        { bg = p.bg_elev2 })
    set("LspReferenceRead",        { bg = p.bg_elev2 })
    set("LspReferenceWrite",       { bg = p.bg_elev2 })
    set("LspSignatureActiveParameter", { fg = p.parameter, italic = true, bold = true })
    set("LspInlayHint",            { fg = p.fg_disabled, italic = true })
    set("LspCodeLens",             { fg = p.fg_muted })
    set("LspCodeLensSeparator",    { fg = p.fg_disabled })

    -- ---------- gitsigns.nvim ----------
    set("GitSignsAdd",             { fg = p.diff_added })
    set("GitSignsChange",          { fg = p.diff_changed })
    set("GitSignsDelete",          { fg = p.diff_removed })
    set("GitSignsAddNr",           { fg = p.diff_added })
    set("GitSignsChangeNr",        { fg = p.diff_changed })
    set("GitSignsDeleteNr",        { fg = p.diff_removed })
    set("GitSignsCurrentLineBlame",{ fg = p.fg_disabled, italic = true })
    set("GitSignsAddInline",       { bg = p.bg_elev1 })
    set("GitSignsChangeInline",    { bg = p.bg_elev1 })
    set("GitSignsDeleteInline",    { bg = p.bg_elev1 })

    -- ---------- telescope.nvim ----------
    set("TelescopeNormal",          { fg = p.fg, bg = p.bg_menu })
    set("TelescopeBorder",          { fg = p.border_strong, bg = p.bg_menu })
    set("TelescopePromptNormal",    { fg = p.fg, bg = p.bg_input })
    set("TelescopePromptBorder",    { fg = p.border_strong, bg = p.bg_input })
    set("TelescopePromptTitle",     { fg = p.fg_inverse, bg = p.primary, bold = true })
    set("TelescopePromptPrefix",    { fg = p.primary })
    set("TelescopePromptCounter",   { fg = p.fg_muted })
    set("TelescopeResultsTitle",    { fg = p.fg_inverse, bg = p.primary })
    set("TelescopePreviewTitle",    { fg = p.fg_inverse, bg = p.primary })
    set("TelescopeSelection",       { fg = p.fg, bg = p.bg_elev2, bold = true })
    set("TelescopeSelectionCaret",  { fg = p.primary, bg = p.bg_elev2 })
    set("TelescopeMatching",        { fg = p.primary, bold = true })
    set("TelescopeMultiSelection",  { fg = p.fg, bg = p.bg_elev1 })
    set("TelescopeMultiIcon",       { fg = p.primary })

    -- ---------- nvim-tree ----------
    set("NvimTreeNormal",          { fg = p.fg, bg = p.bg_sidebar })
    set("NvimTreeNormalNC",        { fg = p.fg, bg = p.bg_sidebar })
    set("NvimTreeWinSeparator",    { fg = p.border, bg = p.bg_sidebar })
    set("NvimTreeRootFolder",      { fg = p.markup_heading, bold = true })
    set("NvimTreeFolderIcon",      { fg = p.primary })
    set("NvimTreeFolderName",      { fg = p.fg })
    set("NvimTreeOpenedFolderName",{ fg = p.fg, bold = true })
    set("NvimTreeEmptyFolderName", { fg = p.fg_muted })
    set("NvimTreeIndentMarker",    { fg = p.border })
    set("NvimTreeSymlink",         { fg = p.markup_link })
    set("NvimTreeFileIcon",        { fg = p.fg_muted })
    set("NvimTreeGitDirty",        { fg = p.diff_changed })
    set("NvimTreeGitNew",          { fg = p.diff_added })
    set("NvimTreeGitDeleted",      { fg = p.diff_removed })
    set("NvimTreeGitStaged",       { fg = p.diff_added })
    set("NvimTreeGitMerge",        { fg = p.warning })
    set("NvimTreeGitRenamed",      { fg = p.info })
    set("NvimTreeGitIgnored",      { fg = p.fg_disabled })
    set("NvimTreeSpecialFile",     { fg = p.markup_heading, underline = true })
    set("NvimTreeCursorLine",      { bg = p.bg_elev1 })

    -- ---------- neo-tree.nvim ----------
    set("NeoTreeNormal",           { fg = p.fg, bg = p.bg_sidebar })
    set("NeoTreeNormalNC",         { fg = p.fg, bg = p.bg_sidebar })
    set("NeoTreeDirectoryIcon",    { fg = p.primary })
    set("NeoTreeDirectoryName",    { fg = p.fg })
    set("NeoTreeFileIcon",         { fg = p.fg_muted })
    set("NeoTreeFileName",         { fg = p.fg })
    set("NeoTreeRootName",         { fg = p.markup_heading, bold = true })
    set("NeoTreeIndentMarker",     { fg = p.border })
    set("NeoTreeSymbolicLinkTarget", { fg = p.markup_link })
    set("NeoTreeGitAdded",         { fg = p.diff_added })
    set("NeoTreeGitConflict",      { fg = p.warning })
    set("NeoTreeGitDeleted",       { fg = p.diff_removed })
    set("NeoTreeGitIgnored",       { fg = p.fg_disabled })
    set("NeoTreeGitModified",      { fg = p.diff_changed })
    set("NeoTreeGitUnstaged",      { fg = p.diff_changed })
    set("NeoTreeGitUntracked",     { fg = p.diff_added })
    set("NeoTreeGitStaged",        { fg = p.diff_added })
    set("NeoTreeFloatBorder",      { fg = p.border_strong, bg = p.bg_menu })
    set("NeoTreeTitleBar",         { fg = p.fg_inverse, bg = p.primary, bold = true })

    -- ---------- lualine support colors ----------
    -- (lualine reads colors via theme tables, but these named groups give a
    -- sensible default if a user picks "auto" theme.)
    set("lualine_a_normal",        { fg = p.fg_inverse, bg = p.primary, bold = true })
    set("lualine_a_insert",        { fg = p.fg_inverse, bg = p.success, bold = true })
    set("lualine_a_visual",        { fg = p.fg_inverse, bg = p.constant, bold = true })
    set("lualine_a_replace",       { fg = p.fg_inverse, bg = p.error,   bold = true })
    set("lualine_a_command",       { fg = p.fg_inverse, bg = p.warning, bold = true })
    set("lualine_b_normal",        { fg = p.fg, bg = p.bg_elev2 })
    set("lualine_c_normal",        { fg = p.fg_muted, bg = p.bg })

    return hi
end

return M
